export enum Genre {
    beats = "Beats",               
    chill_LoFi = "Chill/Lo Fi",         
    dance_EDM = "Dance/EDM",           
    darkpsy_hitech = "Darkpsy/Hitech",      
    deepHouse = "Deep House",          
    dnB_Neurofunk = "DnB/Neurofunk",       
    dubstep = "Dubstep",             
    electronic_downtempo = "Electronic/Downtempo",
    electroHouse = "Electro House",       
    futureHouse = "Future House",        
    house = "House",               
    orchestral = "Orchestral",          
    hardcore_rawstyle = "Hardcore/Rawstyle",   
    progressiveTrance = "Progressive Trance",  
    psytrance = "Psytrance",           
    rap_hipHop = "Rap/Hip Hop",         
    reggae_dancehall = "Reggae/Dancehall",    
    techno = "Techno",              
    techHouse = "Tech House",          
    trance = "Trance",              
    trap = "Trap",
    other = "Other"         
}